In [1]:
import numpy as np

In [2]:
list2 = [3,4,5,6]
print (type(list2))
arr2 = np.array(list2,dtype= float)
type (arr2)
arr2

<class 'list'>


array([3., 4., 5., 6.])

In [3]:
arr2 *= 2
arr2

array([ 6.,  8., 10., 12.])

In [6]:
arr3 = 3
arr3 = arr3+2
arr3

5

In [8]:
type (arr2)

numpy.ndarray

In [9]:
arr3_s = arr2.astype('int').astype('str')
arr3_s

array(['6', '8', '10', '12'], dtype='<U11')

In [10]:
arr_obj = np.array([1,'a'],dtype= 'object')
print  (arr_obj )
type(arr_obj)

[1 'a']


numpy.ndarray

In [11]:
arr_list = arr_obj.tolist()
type(arr_list)

list

In [12]:
list3 = [[1,2,3],[4,5,6],[7,8,9],[3,5,8]]
arr3 = np.array(list3)
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 8]]


In [13]:
arr3.shape

(4, 3)

In [14]:
arr3.dtype
type(arr3)

numpy.ndarray

In [15]:
list22= [5,6,6,11,-3,-3,-1,2,3,8]
list_arr= np.array(list22)
M = list_arr.mean()
M

3.4

In [16]:
SD = list_arr.std()
SD

4.454211490264018

In [17]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])  # a list within a list
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [19]:
# Get Shape
b.shape
# Get Type
a.dtype
# Get number of elements
a.size

3

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# Get a specific element [r, c]
a[1, 5]

13

In [22]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [24]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 6,  2,  4],
       [ 4,  2,  3],
       [ 2, -4,  3]])

In [25]:
# mathematics
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [27]:
a + 2

array([0.5, 1. , 1.5, 2. ])

In [28]:
a - 2

array([-1,  0,  1,  2])

In [29]:
a * 2

array([2, 4, 6, 8])

In [30]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [31]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [32]:
a ** 2

array([ 1,  4,  9, 16])

In [33]:
#Creating and accessing numpy array
l = [1, 2, 3, 4, 5]
print((l), type(l))
# 1D Array
# a = np.array([1, 2, 3, 4, 5])
# Creation dtype is optional
a = np.array(l, dtype='float64')
print((a, type(a), a.dtype))

# using arange
a2 = np.arange(9)
a3 = np.arange(1,10)
a4 = np.arange(1,10,3, dtype='float')
print(a2)
print(a3)
print(a4)

# Getting elements and slicing
print(a)
print(a[-2])
print(a[3])
print(a[1:-1])
print(a[1:5])


[1, 2, 3, 4, 5] <class 'list'>
(array([1., 2., 3., 4., 5.]), <class 'numpy.ndarray'>, dtype('float64'))
[0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
[1. 4. 7.]
[1. 2. 3. 4. 5.]
4.0
4.0
[2. 3. 4.]
[2. 3. 4. 5.]


In [34]:
# Multi Dimentional Array Creation and selection
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a[1,1])
print(a[1,2])

b = np.arange(11,20)
print(b)
b = b.reshape((3,3))
print(b)
c = np.arange(11,23).reshape((4,3))
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
6
[11 12 13 14 15 16 17 18 19]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [35]:
# Slicing
print(c)
print(c[1:3,1:])
print(c[2,1])

# Explore slicing with -

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[15 16]
 [18 19]]
18


In [36]:
# array of zeros or ones and random integer with certain dimention
# Zeros
z = np.zeros((5,4))
print(z)
# Ones
o = np.ones((3,4))
print(o)
# Random
r = np.random.randint(1,100, (6,6))
print(r)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[68 84 65 21 30 14]
 [51 87 96 19 99 88]
 [88 60 98 67 21 28]
 [85  2 41 58 74 95]
 [45  4 14  7 35 55]
 [11 50 63 49  7 64]]


In [37]:
# Flattening multi d array to 1 d array using flatten
print(r)
print(r.flatten())


[[68 84 65 21 30 14]
 [51 87 96 19 99 88]
 [88 60 98 67 21 28]
 [85  2 41 58 74 95]
 [45  4 14  7 35 55]
 [11 50 63 49  7 64]]
[68 84 65 21 30 14 51 87 96 19 99 88 88 60 98 67 21 28 85  2 41 58 74 95
 45  4 14  7 35 55 11 50 63 49  7 64]


In [38]:
# Transpose row to col and vice versa using transpose
na = np.arange(10,20).reshape(5,2)
print(na)
na_transposed = na.transpose()
print(na_transposed)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[10 12 14 16 18]
 [11 13 15 17 19]]


In [39]:
#basic funcationalities
# type(), dtype, ndim, shape, size, 
print(na)
print(type(na))
print(na.dtype)
print(na.ndim)
print(na.shape)
print(na.size)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
<class 'numpy.ndarray'>
int32
2
(5, 2)
10


In [40]:
# Calculation with given number
print(na)
print(na+2)
print(na**2)
print(na%2)
print(na//2)
print(na/2)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]
[[100 121]
 [144 169]
 [196 225]
 [256 289]
 [324 361]]
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
[[5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]
[[5.  5.5]
 [6.  6.5]
 [7.  7.5]
 [8.  8.5]
 [9.  9.5]]


In [41]:
# Calculation with two different arrays
a1 = na
a2 = na+2
print(a1)
print(a2)
print(a2-a1)
print(a2/a1)
print(a2+a1)
print(a2*a1)
print(a2**a1)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1.2        1.18181818]
 [1.16666667 1.15384615]
 [1.14285714 1.13333333]
 [1.125      1.11764706]
 [1.11111111 1.10526316]]
[[22 24]
 [26 28]
 [30 32]
 [34 36]
 [38 40]]
[[120 143]
 [168 195]
 [224 255]
 [288 323]
 [360 399]]
[[1787822080 1159031605]
 [ 344068096 -642346289]
 [         0 2116147697]
 [1048641536 1046123219]
 [         0  547383789]]


In [42]:
#type casting
# crete int array
a = np.arange(1,6)
print((a, a.dtype))
# convert to float
af = a.astype('float64')
print((af, af.dtype))

# convert to string
a_s = a.astype('str')
print((a_s, a_s.dtype))
# convert to object
a_o = a.astype('object')
print((a_o, a_o.dtype))

(array([1, 2, 3, 4, 5]), dtype('int32'))
(array([1., 2., 3., 4., 5.]), dtype('float64'))
(array(['1', '2', '3', '4', '5'], dtype='<U11'), dtype('<U11'))
(array([1, 2, 3, 4, 5], dtype=object), dtype('O'))


In [43]:
#convert from list to array
# Create list
l = [3, 4, 5, 6]
print((l, type(l)))
# list to np array
a = np.array(l)
print((a, type(a)))
# np array to list
l1 = a.tolist()
print((l, type(l1)))

([3, 4, 5, 6], <class 'list'>)
(array([3, 4, 5, 6]), <class 'numpy.ndarray'>)
([3, 4, 5, 6], <class 'list'>)


In [44]:
# statical methods
# min, max, mean, std
print(a)
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

[3 4 5 6]
3
6
4.5
1.118033988749895
