In [36]:
print("My name is Alish Maharjan")
print(1)
print(2.3)
print(True)
print((True, False))

My name is Alish Maharjan
1
2.3
True
(True, False)


In [37]:
print(12 + 13)
print(13-12)

print(12*13)
print(24/12)

print(3**3)

print(5%2) # Remainder
print(5//2) # Quotent

25
1
156
2.0
27
1
2


In [38]:
# Comparison operator
print(23==23) # equals to  
print(23!=23) # not equals to 

print(23>23)
print(23<23)

print(23>=23)
print(23<=23)

True
False
False
False
True
True


In [39]:
# Assignment operators
a = 10
b = 20

print((a, b))

a += 20
b -= 10

print((a, b))

a *= 2
print(a)

(10, 20)
(30, 10)
60


In [40]:
#logical operator
print(True and False)
print(True or False)
print(not True)

b = 16
print(b>10 and b<15)

if(b>10 and b<15):
    print(True)

False
True
False
False


In [41]:
# bitwise operator
# and = &, or= |
print(True & False)
print(True | False)
# print(!(20 = 20))

b = 16
print(b>10 & b<15)

if(b>10 & b<15):
    print(True)

False
True
True
True


In [42]:
# string
grade = 'a'
name = "Rajesh Hamal"
print(grade, type(grade))
print(name, type(name))
# integer
a = 10
print(a, type(a))
# float
b = 23.4
print(b, type(b))
# boolean
workDone = True
print(workDone, type(workDone))

a <class 'str'>
Rajesh Hamal <class 'str'>
10 <class 'int'>
23.4 <class 'float'>
True <class 'bool'>


In [43]:
# Collection data type
# list, dictionary, tuple
marks = [23, 45, 67, 89]
toPrint = (marks, type(marks))
print(toPrint)
print(type(toPrint))


student = {'name':'Rajesh Hamal', 'Age': 23, 'graduated': True}
print((student, type(student)))

([23, 45, 67, 89], <class 'list'>)
<class 'tuple'>
({'name': 'Rajesh Hamal', 'Age': 23, 'graduated': True}, <class 'dict'>)


In [44]:
#Arthmetic_Functions
a = 10
name = "Ram"
phone = 9863033649
b = 20
print(a+b)

30


In [45]:
name, age, phone, email = "Ramesh", 34, 9847654564, "ramesh@abc.com"
print((name, age, phone, email))

('Ramesh', 34, 9847654564, 'ramesh@abc.com')


In [46]:
# student1qualification
s1q = s2q = s3q = "Graduated"
print((s1q, s2q, s3q))

('Graduated', 'Graduated', 'Graduated')


In [47]:
a = 20
b = 15

remainder = a%b
quotent = a//b

print(f"Remainder is {remainder}, Quotent is {a//b}")

print(type(quotent))

float_quotent = float(quotent)
print((float_quotent, type(float_quotent)))

print(type(int(float_quotent)))

marks1 = 75.2
marks_rounded = round(marks1)
print(marks_rounded)

Remainder is 5, Quotent is 1
<class 'int'>
(1.0, <class 'float'>)
<class 'int'>
75


In [48]:
# string concatination
s1 = "My name is Ram "
s2 = "I am 23"
ram = s1 + s2
print(ram)

My name is Ram I am 23


In [49]:
name = "Ram"
age = 23
# F string
print(f"My name is {name}, I am {age}")
#Format function
print("My name is {}, I am {}".format(name, age))
# % operator
print("My name is %s, I am %d" %(name,age))

My name is Ram, I am 23
My name is Ram, I am 23
My name is Ram, I am 23


In [50]:
# (len, min, max, str.index("a"), str.find("a"), str.count("a"), .lower(), .upper(), .strip("a"), .startswith(),  .replace(old, new), .split(","), delim.join(list))
ram = f"My name is {name}, I am {age}"
print(ram)

print(len(ram))
print((min('abcdz'), max('abcdz')))

My name is Ram, I am 23
23
('a', 'z')


In [51]:
# property functions
print(ram)
print((ram.index('a'), ram.find('a')))
# Research about differences between find and index
# Research about .strip("a"), .startswith(),

print(ram.count('R'))

print((ram.lower(), ram.upper()))
ram_upper = ram.upper()

My name is Ram, I am 23
(4, 4)
1
('my name is ram, i am 23', 'MY NAME IS RAM, I AM 23')


In [52]:
hari = ram.replace("Ram", "Hari")
print(hari)

text = "Ram, 24, student"
text_list = text.split(',')
print(text_list)

My name is Hari, I am 23
['Ram', ' 24', ' student']


In [53]:
hari_list = hari.split(' ')
print(hari_list)

joined_list = (" ").join(hari_list)
print(joined_list)
# help('str.join')

['My', 'name', 'is', 'Hari,', 'I', 'am', '23']
My name is Hari, I am 23


In [54]:
#Conditionals

num1 = 300
num2 = 300

if(num1>num2):
    print(f"{num1} is greater")
elif(num1 == num2):
    print("Both the numbers are equal")
else:
    print(f"{num2} is greater")

Both the numbers are equal


In [55]:
#loops
age = [23,34,56,65]
for i in age:
    print(i)

23
34
56
65


In [56]:
for i in range(1,23, 2):
    print(i)

1
3
5
7
9
11
13
15
17
19
21


In [57]:
help('if')
help('len')
help('max')
help('str.upper')

The "if" statement
******************

The "if" statement is used for conditional execution:

   if_stmt ::= "if" assignment_expression ":" suite
               ("elif" assignment_expression ":" suite)*
               ["else" ":" suite]

It selects exactly one of the suites by evaluating the expressions one
by one until one is found to be true (see section Boolean operations
for the definition of true and false); then that suite is executed
(and no other part of the "if" statement is executed or evaluated).
If all expressions are false, the suite of the "else" clause, if
present, is executed.

Related help topics: TRUTHVALUE

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keywor

In [7]:
#python list
l = [1, 2, 3, 4]
print((l), type(l))

#into numpy array
a = np.array(l, dtype='float64')
print((a), type(a), a.dtype)

#arange function
a2 = np.arange(9)
a3 = np.arange(1, 10)
a4 = np.arange(1, 10, 3, dtype='float')
print(a2)
print(a3)
print(a4)

#slicing
print(a[1:3])
print(a[3])

#multi-dimentional array
a = np.array([[11,12,13], [14,15,16], [17,18,19]])
print(a)

b = np.arange(11,19)
print(b)

b = np.reshape(b, (2, 4)) 
print(b)

#transposed
#rows bata column ma change hunxa


#basic functionalities



[1, 2, 3, 4] <class 'list'>
[1. 2. 3. 4.] <class 'numpy.ndarray'> float64
[0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
[1. 4. 7.]
[2. 3.]
4.0
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[11 12 13 14 15 16 17 18]
[[11 12 13 14]
 [15 16 17 18]]


In [8]:
#type casting

a = np.arange(1, 6)
print((a, a.dtype))

af = a.astype('float64')
print((af, af.dtype))

a_s = a.astype('str')
print((a_s, a_s.dtype))

a_o = a.astype('object')
print((a_o, a_o.dtype))

(array([1, 2, 3, 4, 5]), dtype('int32'))
(array([1., 2., 3., 4., 5.]), dtype('float64'))
(array(['1', '2', '3', '4', '5'], dtype='<U11'), dtype('<U11'))
(array([1, 2, 3, 4, 5], dtype=object), dtype('O'))


In [9]:
#statical measures

#min, max, mean, std
print(a)
print(a.min())
print(a.max())
print(a.mean())
print(a.std()) 

#conversion
l = [1, 2, 3, 4]
print((l, type(l)))

a = np.array(l)
print((a, type(a)))

li = a.tolist()
print((li, type(li)))


[1 2 3 4 5]
1
5
3.0
1.4142135623730951
([1, 2, 3, 4], <class 'list'>)
(array([1, 2, 3, 4]), <class 'numpy.ndarray'>)
([1, 2, 3, 4], <class 'list'>)


In [11]:
d1 = {
    'name' : ['Ram', 'Shyam', 'Sita', 'Gita', 'Hari'],
    'marks' : [56.1, 67.12, 98, 45, 85],
    'rollno' : [1, 3, 2, 5, 7]
}

In [12]:
df = pd.DataFrame(d1)
print(df)

    name  marks  rollno
0    Ram  56.10       1
1  Shyam  67.12       3
2   Sita  98.00       2
3   Gita  45.00       5
4   Hari  85.00       7


In [13]:
#export datafrome into csv
df.to_csv('marks_data.csv', index=False)

In [14]:
#importing from CSV
student_df = pd.read_csv('marks_data.csv')
print(student_df)

    name  marks  rollno
0    Ram  56.10       1
1  Shyam  67.12       3
2   Sita  98.00       2
3   Gita  45.00       5
4   Hari  85.00       7


In [15]:
#basic functionalities 

print(student_df.shape)
print(student_df.size)

(5, 3)
15


In [16]:
#summary statistics haru dinxa
student_df.describe()

marks    rollno
count   5.000000  5.000000
mean   70.244000  3.600000
std    21.419656  2.408319
min    45.000000  1.000000
25%    56.100000  2.000000
50%    67.120000  3.000000
75%    85.000000  5.000000
max    98.000000  7.000000

In [17]:
student_df['marks'].describe()

count     5.000000
mean     70.244000
std      21.419656
min      45.000000
25%      56.100000
50%      67.120000
75%      85.000000
max      98.000000
Name: marks, dtype: float64

In [18]:
#dtype

print(type(student_df))
print(student_df.dtypes)

<class 'pandas.core.frame.DataFrame'>
name       object
marks     float64
rollno      int64
dtype: object


In [19]:
#columns, index
#() vako vaneko function ho ani navako vaneko properties ho
print(student_df.columns)

Index(['name', 'marks', 'rollno'], dtype='object')


In [20]:
student_df.head()

name  marks  rollno
0    Ram  56.10       1
1  Shyam  67.12       3
2   Sita  98.00       2
3   Gita  45.00       5
4   Hari  85.00       7

In [21]:
student_df.tail()

name  marks  rollno
0    Ram  56.10       1
1  Shyam  67.12       3
2   Sita  98.00       2
3   Gita  45.00       5
4   Hari  85.00       7

In [22]:
student_df.head(2)


name  marks  rollno
0    Ram  56.10       1
1  Shyam  67.12       3

In [23]:
student_df.tail(3)

name  marks  rollno
2  Sita   98.0       2
3  Gita   45.0       5
4  Hari   85.0       7

In [24]:
#values in numpy array
import numpy as np
student_np = student_df.values
print(type(student_np))
print(student_np)

<class 'numpy.ndarray'>
[['Ram' 56.1 1]
 ['Shyam' 67.12 3]
 ['Sita' 98.0 2]
 ['Gita' 45.0 5]
 ['Hari' 85.0 7]]


In [25]:
#transpose (which means rows lai column and viceversa)
print(student_df.T)

           0      1     2     3     4
name     Ram  Shyam  Sita  Gita  Hari
marks   56.1  67.12  98.0  45.0  85.0
rollno     1      3     2     5     7


In [26]:
#sorting dataframe and inplace=True garyo vane chai present dataframe save hunxa
student_df.sort_values(by="marks",ascending=False, inplace=True)
print(student_df)

    name  marks  rollno
2   Sita  98.00       2
4   Hari  85.00       7
1  Shyam  67.12       3
0    Ram  56.10       1
3   Gita  45.00       5


In [27]:
#slicing dataframe usinf iloc / iloc use garyo vane index default hunxa
student_df.iloc[2:4, 0:-1]

#[column , rows]


name  marks
1  Shyam  67.12
0    Ram  56.10

In [28]:
#finding null values

#yo chai etkai khali gareko

student_df.iloc[1, 1] = None
student_df

name  marks  rollno
2   Sita  98.00       2
4   Hari    NaN       7
1  Shyam  67.12       3
0    Ram  56.10       1
3   Gita  45.00       5

In [29]:
student_df.isnull()

name  marks  rollno
2  False  False   False
4  False   True   False
1  False  False   False
0  False  False   False
3  False  False   False

In [30]:
student_df.isnull().sum()

name      0
marks     1
rollno    0
dtype: int64

In [31]:
student_df.isnull().sum().sum()

1

In [32]:
#[[]] = subset leyo vane yauta value vanda badi mark garna milxa

numeric_df = student_df[['marks', 'rollno']]
numeric_df


marks  rollno
2  98.00       2
4    NaN       7
1  67.12       3
0  56.10       1
3  45.00       5

In [33]:
#summary statistics

print(numeric_df['marks'].mean())
print(numeric_df['marks'].median())
print(numeric_df['marks'].mode()[0])
print(numeric_df['marks'].min())
print(numeric_df['marks'].max())
print(numeric_df['marks'].sum())
print(numeric_df['marks'].quantile(.25))
print(numeric_df['marks'].quantile(.50))
print(numeric_df['marks'].quantile(.75))

66.555
61.61
45.0
45.0
98.0
266.22
53.325
61.61
74.84
